name: docker

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  multi-registries:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: caffix/amass
          tag-semver: |
            v{{major}}
            v{{major}}.{{minor}}
            v{{major}}.{{minor}}.{{patch}}
      -
        name: set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
